//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abdullin_kurs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AbdullinDBEntities : DbContext
    {
        public static AbdullinDBEntities _context;
        public static AbdullinDBEntities GetContext()

        {
            if (_context == null)
                _context = new AbdullinDBEntities();
            return _context;
        }
        public AbdullinDBEntities()
            : base("name=AbdullinDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ведомость_успеваемости> Ведомость_успеваемости { get; set; }
        public virtual DbSet<Дисциплины> Дисциплины { get; set; }
        public virtual DbSet<Кафедры> Кафедры { get; set; }
        public virtual DbSet<Преподаватели> Преподаватели { get; set; }
        public virtual DbSet<Студенты> Студенты { get; set; }
        public virtual DbSet<Учебные_группы> Учебные_группы { get; set; }
        public virtual DbSet<Факультеты> Факультеты { get; set; }
    }
}
