//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abdullin_kurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ведомость_успеваемости
    {
        public int Ведомость_ID { get; set; }
        public int Группа_ID { get; set; }
        public int Дисциплина_ID { get; set; }
        public int Преподаватель_ID { get; set; }
        public Nullable<int> Учебный_год { get; set; }
        public Nullable<int> Семестр { get; set; }
        public int Студент_ID { get; set; }
        public Nullable<int> Оценка { get; set; }
    
        public virtual Дисциплины Дисциплины { get; set; }
        public virtual Преподаватели Преподаватели { get; set; }
        public virtual Студенты Студенты { get; set; }
        public virtual Учебные_группы Учебные_группы { get; set; }
    }
}
