//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abdullin_kurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Дисциплины
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Дисциплины()
        {
            this.Ведомость_успеваемости = new HashSet<Ведомость_успеваемости>();
        }
    
        public int Дисциплина_ID { get; set; }
        public int Кафедра_ID { get; set; }
        public int Преподаватель_ID { get; set; }
        public string Название_дисциплины { get; set; }
        public Nullable<int> Часовка { get; set; }
        public string Форма_контроля { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ведомость_успеваемости> Ведомость_успеваемости { get; set; }
        public virtual Кафедры Кафедры { get; set; }
    }
}
