//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abdullin_kurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Кафедры
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Кафедры()
        {
            this.Дисциплины = new HashSet<Дисциплины>();
            this.Преподаватели = new HashSet<Преподаватели>();
            this.Учебные_группы = new HashSet<Учебные_группы>();
        }
    
        public int Кафедра_ID { get; set; }
        public int Факультет_ID { get; set; }
        public string Название_кафедры { get; set; }
        public string ФИО_заведующего { get; set; }
        public string Номер_комнаты { get; set; }
        public string Номер_корпуса { get; set; }
        public string Телефон_кафедры { get; set; }
        public Nullable<int> Кол_во_преподавателей { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Дисциплины> Дисциплины { get; set; }
        public virtual Факультеты Факультеты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Преподаватели> Преподаватели { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Учебные_группы> Учебные_группы { get; set; }
    }
}
