//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abdullin_kurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Преподаватели
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Преподаватели()
        {
            this.Ведомость_успеваемости = new HashSet<Ведомость_успеваемости>();
        }
    
        public int Преподаватель_ID { get; set; }
        public int Кафедра_ID { get; set; }
        public string ФИО { get; set; }
        public string Должность { get; set; }
        public string Научное_звание { get; set; }
        public Nullable<decimal> Ставка { get; set; }
        public Nullable<decimal> Стаж_работы { get; set; }
        public string Адрес_проживания { get; set; }
        public Nullable<int> Возраст { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ведомость_успеваемости> Ведомость_успеваемости { get; set; }
        public virtual Кафедры Кафедры { get; set; }
    }
}
