//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abdullin_kurs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Факультеты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Факультеты()
        {
            this.Кафедры = new HashSet<Кафедры>();
        }
    
        public int Факультет_ID { get; set; }
        public string Название_факультета { get; set; }
        public string ФИО_декана { get; set; }
        public string Номер_комнаты { get; set; }
        public string Номер_корпуса { get; set; }
        public string Телефон_деканата { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Кафедры> Кафедры { get; set; }
    }
}
